name: Hello François

on: workflow_dispatch
env: 
  NAME: Hanen

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: "DIT bonjour"

        if: ${{ env.NAME != 'Hanen'}}
        run: echo "Salut mais qui es tu> tu n'es pas $NAME ?! OO!"

      - name: "Hello hanen"


        if: ${{ env.NAME == 'François'}}
        run: echo "Salut $NAME ? Force et honneur!"
