# name: Amnesia

# on: workflow_dispatch
# env: 
#   NAME: Hanen

# jobs:
#   say_hello:
#     runs-on: ubuntu-latest
#     env:
#       ENTREPRISE: semifir
#     steps:
#       - name: "Dite bonjour"
#         run: echo "Salut $NAME ! Tu travailles chez $ENTREPRISE? alors bon $DAY à toi!"
#         env:
#           DAY:  mardi
#       - name: "Mardi ?"
#         run: echo "Quel jour sommes nous? $DAY ?"
#   say_goodbye:
#     runs-on:  ubuntu-latest
#     steps:
#       - name: "DITE au revoir"
#         run: echo "Au revoir $NAME ! Tu travilles chez $ENTREPRISE ? alors bon $DAY à toi!"
       
