# name: Workflow Liés

# on:
#   workflow_dispatch:  # lancement manuel

# jobs:
#   premier-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Message Job 1
#         run: echo "Le premier job a été exécuté manuellement"

#   second-job:
#     runs-on: ubuntu-latest
#     needs: premier-job  # dépend du premier job
#     steps:
#       - name: Message Job 2
#         run: echo "Le second job s'exécute après le premier"
