name: Fruits Matrix

on:
  workflow_dispatch:

jobs:
  manger:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        fruit: [pomme, banane, orange, fraise]
        nom: [Michel, Sophie, Lucas]

    steps:
      - name: Afficher une phrase
        run: echo "${{ matrix.nom }} mange une ${{ matrix.fruit }}, et il adore Ã§a !"
